ilovespace/ilovespace/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts import views as acc_views
from django.contrib.auth import views as Auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',acc_views.HomePage.as_view(),name = 'home'),
    path('login/',Auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('accounts/login/',Auth_views.LoginView.as_view(template_name="accounts/login.html"),name='accounts_login'),
    path('logout/',Auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',acc_views.SignUp.as_view(),name="signup"),
    path('posts/',include('posts.urls',namespace='posts')),
    path('groups/',include('groups.urls',namespace='groups')),
]

ilovespace/posts/urls.py
from django.urls import path

from . import views

app_name='posts'

urlpatterns = [
    path("", views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/(<username>[-\w]+)/",views.UserPosts.as_view(),name="for_user"),
    path("by/(<username>[-\w]+)/(<pk>\d+)/",views.PostDetail.as_view(),name="single"),
    path("delete/(<pk>\d+)/",views.DeletePost.as_view(),name="delete"),
]

ilovespace/accounts/models.py
from django.db import models

from django.contrib import auth
# Create your models here.

class User(auth.models.User,auth.models.PermissionsMixin):
    def __str__(self):
        return f'@{self.username}'

ilovespace/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
# from django.contrib.auth import get_user_model


class UserCreateForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username','email','password1','password2']
    # def __init__(self,*args,**kwargs):
    #     super().__init__(*args,**kwargs)
    #     self.fields['username'].label = "Dispaly Name"
    #     self.fields['email'].label = "Email Address"
        

ilovespace/accounts/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView
from django.urls import reverse_lazy
from .forms import UserCreateForm
# Create your views here.
class HomePage(TemplateView):
    template_name = 'accounts/home.html'

class SignUp(CreateView):
    form_class = UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

ilovespace/accounts/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <!-- <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Signika:wght@300&display=swap" rel="stylesheet"> -->
    <link rel="stylesheet" href="{% static 'ilovespace/css/master.css' %}">
    
    <title>IloveSpace</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Star Social Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'posts:create' %}">Post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'groups:all' %}">Groups</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'groups:create' %}">Create Group</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'groups:all' %}">Groups</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'signup'%}">SignUp</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
      <div class="container mycontent">
        {% block body %}
        {% endblock %}
      </div>
      
<canvas id="canvas"></canvas>
</body>

<script type="text/javascript" src="{% static 'ilovespace/js/master.js' %}"></script>
</html>

ilovespace/accounts/templates/accounts/home.html
{% extends 'accounts/base.html' %}
{% block body %}
<h1>
<div class="container">Welcome to the space lover app</div>
</h1>
<h3>
    <div class="container">Here You will find people who loves to talk about space.</div>
    <div class="container">Hope You enjoy the Posts and the social groups here</div>
    </h3>
{% endblock %}

ilovespace/accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load bootstrap5 %}
{% block body %}
<div class="container">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-default" value="Login">

    </form>
</div>
{% endblock %}

ilovespace/accounts/templates/accounts/signup.html
{% extends 'accounts/base.html' %}
{% load bootstrap5 %}
{% block body %}
<div class="container">
    <h1>Sign Up</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-default" value="Sign Up">

    </form>
</div>
{% endblock %}